[package]
name = "afterglow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.2"
minifb = { version = "0.23.0", optional = true }
nokhwa = { version = "0.9.4", features = ["input-v4l", "input-msmf", "input-avfoundation"] }
rayon = "1.5.3"
rppal = { version = "0.13.1", optional = true }

[features]
visual = ["minifb"]
rpi = ["rppal"]
