[package]
name = "afterglow"
version = "0.1.0"
edition = "2021"
default-run = "afterglow-debug"

[[bin]]
name = "afterglow-debug"
path = "src/main.rs"

[[bin]]
name = "afterglow"
path = "src/afterglow.rs"
test = false
bench = false
doc = false
required-features = ["rpi"]

[dependencies]
dialoguer = "0.10.2"
minifb = "0.23.0"
nokhwa = { version = "0.9.4", features = ["input-v4l", "input-msmf", "input-avfoundation"] }
rayon = "1.5.3"
rppal = { version = "0.13.1", optional = true }

[features]
rpi = ["rppal"]
